# Generated by Django 6.0.1 on 2026-04-28 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='mentor_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='mentor_reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
