# Generated by Django 6.0.1 on 2026-04-28 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todoitem_mentor_comment_todoitem_mentor_reviewed'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='todolist',
            unique_together=set(),
        ),
    ]
