# Generated by Django 6.0 on 2026-01-31 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyreport',
            old_name='tomorrow_goals',
            new_name='next_steps',
        ),
    ]
