# Generated by Django 6.0.1 on 2026-04-17 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20260131_0303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='next_steps',
            field=models.TextField(help_text='Your plans, action items, or goals for the next session/day'),
        ),
    ]
